// 单据生成 — Document Generation
// BOL (提单) / Packing Slip (装箱单) / Commercial Invoice

import { createServiceClient } from "@/lib/supabase";

export interface DocumentData {
  orderId: string;
  type: "bol" | "packing_slip" | "commercial_invoice";
  shipmentId?: string;
}

interface OrderInfo {
  id: string;
  externalOrderId?: string;
  status?: string;
  shippingName?: string;
  shippingAddress1?: string;
  shippingAddress2?: string;
  shippingCity?: string;
  shippingState?: string;
  shippingZip?: string;
  shippingCountry?: string;
  shippingPhone?: string;
  items: any[];
  packages: any[];
  warehouse?: any;
}

export async function generateDocument(
  tenantId: string,
  docData: DocumentData
): Promise<{ html: string; type: string; orderId: string } | null> {
  const supabase = createServiceClient();
  if (!supabase) return null;

  // 获取订单
  const { data: order } = await supabase
    .from("orders")
    .select("*, order_items(*, products(name, sku)), packages(*), shipments(*)")
    .eq("id", docData.orderId)
    .eq("tenant_id", tenantId)
    .single();

  if (!order) return null;

  const info: OrderInfo = {
    id: (order as any).id,
    externalOrderId: (order as any).external_order_id,
    status: (order as any).status,
    shippingName: (order as any).shipping_name,
    shippingAddress1: (order as any).shipping_address1,
    shippingAddress2: (order as any).shipping_address2,
    shippingCity: (order as any).shipping_city,
    shippingState: (order as any).shipping_state,
    shippingZip: (order as any).shipping_zip,
    shippingCountry: (order as any).shipping_country,
    shippingPhone: (order as any).shipping_phone,
    items: (order as any).order_items || [],
    packages: (order as any).packages || [],
    warehouse: (order as any).warehouses || null,
  };

  switch (docData.type) {
    case "bol": return { html: generateBOL(info), type: "bol", orderId: docData.orderId };
    case "packing_slip": return { html: generatePackingSlip(info), type: "packing_slip", orderId: docData.orderId };
    case "commercial_invoice": return { html: generateCommercialInvoice(info), type: "commercial_invoice", orderId: docData.orderId };
  }
}

function generateBOL(info: OrderInfo): string {
  const totalQty = info.items.reduce((s: number, i: any) => s + (i.quantity_ordered || 0), 0);
  const totalWeight = info.packages.reduce((s: number, p: any) => s + (p.weight_lbs || 0), 0);

  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Bill of Lading</title>
<style>body{font-family:Arial,sans-serif;padding:40px;max-width:800px;margin:0 auto;color:#1a1a1a}
h1{font-size:22px;margin-bottom:4px}h2{font-size:14px;color:#666;margin-top:0}
.section{margin:20px 0;border-top:1px solid #ddd;padding-top:12px}
.row{display:flex;justify-content:space-between;margin:4px 0}
.label{color:#666;font-size:11px;text-transform:uppercase}
table{width:100%;border-collapse:collapse;margin:12px 0}
th,td{border:1px solid #ddd;padding:8px 10px;font-size:12px;text-align:left}
th{background:#f5f5f5}.total{font-weight:bold}
.footer{margin-top:30px;font-size:10px;color:#999;text-align:center}</style></head><body>
<h1>Bill of Lading</h1><h2>BOL #${info.id.slice(0, 8).toUpperCase()} | Order ${info.externalOrderId || info.id.slice(0, 8)}</h2>

<div class="section"><div class="label">Shipper</div>
<div>Flowrid 3PL</div><div>${info.warehouse?.name || ""} — ${[info.warehouse?.city, info.warehouse?.state].filter(Boolean).join(", ")}</div></div>

<div class="section"><div class="label">Consignee</div>
<div>${info.shippingName || "—"}</div>
<div>${[info.shippingAddress1, info.shippingAddress2, info.shippingCity, info.shippingState, info.shippingZip, info.shippingCountry].filter(Boolean).join(", ")}</div></div>

<div class="section">
<div class="row"><span class="label">Total Pieces:</span><span>${info.packages.length}</span></div>
<div class="row"><span class="label">Total Quantity:</span><span>${totalQty}</span></div>
<div class="row"><span class="label">Total Weight:</span><span>${totalWeight.toFixed(1)} lbs</span></div>
</div>

<table><thead><tr><th>Item</th><th>SKU</th><th>Qty</th><th>Weight</th></tr></thead><tbody>
${info.items.map((i: any) => `<tr><td>${i.products?.name || "—"}</td><td>${i.sku || "—"}</td><td>${i.quantity_ordered}</td><td>${i.products?.unit_weight_lbs || "—"}</td></tr>`).join("")}
</tbody></table>

<div class="footer">Generated by Flowrid — ${new Date().toISOString().split("T")[0]}</div>
</body></html>`;
}

function generatePackingSlip(info: OrderInfo): string {
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Packing Slip</title>
<style>body{font-family:Arial,sans-serif;padding:40px;max-width:800px;margin:0 auto;color:#1a1a1a}
h1{font-size:20px;margin-bottom:4px}h2{font-size:13px;color:#666;margin-top:0}
.section{margin:16px 0;border-top:1px solid #ddd;padding-top:10px}
table{width:100%;border-collapse:collapse;margin:10px 0}
th,td{border:1px solid #ddd;padding:6px 8px;font-size:11px;text-align:left}
th{background:#f5f5f5}.check{text-align:center;width:40px}
.footer{font-size:10px;color:#999;text-align:center;margin-top:20px}</style></head><body>
<h1>Packing Slip</h1><h2>Order ${info.externalOrderId || info.id.slice(0, 8)}</h2>

<div class="section"><strong>Ship To:</strong><br/>${info.shippingName || "—"}<br/>${[info.shippingAddress1, info.shippingAddress2, info.shippingCity, info.shippingState, info.shippingZip].filter(Boolean).join("<br/>")}</div>

<table><thead><tr><th>Item</th><th>SKU</th><th class="check">Ordered</th><th class="check">Shipped</th><th>Notes</th></tr></thead><tbody>
${info.items.map((i: any) => `<tr>
<td>${i.products?.name || "—"}</td><td>${i.sku || "—"}</td>
<td class="check">${i.quantity_ordered}</td>
<td class="check">${i.quantity_shipped || i.quantity_packed || i.quantity_ordered}</td>
<td></td></tr>`).join("")}
</tbody></table>

${info.packages.length > 0 ? `<p style="font-size:11px;color:#666;">Packages: ${info.packages.map((p: any) => `${p.tracking_number || p.id?.slice(0,8)} (${p.weight_lbs || "?"} lbs)`).join(", ")}</p>` : ""}

<div class="footer">Packed by: ___________ &nbsp;&nbsp; Date: ${new Date().toISOString().split("T")[0]}</div>
</body></html>`;
}

function generateCommercialInvoice(info: OrderInfo): string {
  const totalValue = info.items.reduce((s: number, i: any) => s + (i.unit_price || 0) * (i.quantity_ordered || 0), 0);
  return `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Commercial Invoice</title>
<style>body{font-family:Arial,sans-serif;padding:40px;max-width:800px;margin:0 auto;color:#1a1a1a}
h1{font-size:20px;margin-bottom:4px}h2{font-size:13px;color:#666;margin-top:0}
.section{margin:16px 0;border-top:1px solid #ddd;padding-top:10px}
.row{display:flex;justify-content:space-between;margin:4px 0}
table{width:100%;border-collapse:collapse;margin:10px 0}
th,td{border:1px solid #ddd;padding:6px 8px;font-size:11px;text-align:left}
th{background:#f5f5f5}.right{text-align:right}
.footer{margin-top:20px;font-size:9px;color:#999;text-align:center}</style></head><body>
<h1>Commercial Invoice</h1><h2>Order ${info.externalOrderId || info.id.slice(0, 8)}</h2>

<div class="row"><span><strong>From:</strong><br/>Flowrid 3PL<br/>${info.warehouse?.name || ""}</span>
<span><strong>To:</strong><br/>${info.shippingName || "—"}<br/>${info.shippingCountry || "—"}</span></div>

<table><thead><tr><th>Description</th><th>HS Code</th><th>Qty</th><th class="right">Unit Price</th><th class="right">Total</th></tr></thead><tbody>
${info.items.map((i: any) => `<tr>
<td>${i.products?.name || i.sku || "—"}</td><td>—</td>
<td>${i.quantity_ordered}</td>
<td class="right">$${parseFloat(i.unit_price || 0).toFixed(2)}</td>
<td class="right">$${(parseFloat(i.unit_price || 0) * i.quantity_ordered).toFixed(2)}</td>
</tr>`).join("")}
</tbody></table>

<div class="row"><strong>Total Value:</strong><strong>$${totalValue.toFixed(2)} USD</strong></div>
<div class="footer">Country of Origin: — &nbsp;|&nbsp; Terms: DAP &nbsp;|&nbsp; Generated ${new Date().toISOString().split("T")[0]}</div>
</body></html>`;
}

/**
 * 生成 PDF（占位 — 实际集成需 puppeteer/html-pdf）
 */
export async function generatePDF(tenantId: string, docData: DocumentData): Promise<Buffer | null> {
  const doc = await generateDocument(tenantId, docData);
  if (!doc) return null;
  // TODO: 集成 PDF 生成库
  return Buffer.from(doc.html, "utf-8");
}
