/** 平台名称 → 图标路径映射（从 3PLCard 提取为共享常量） */
export const PLATFORM_ICONS: Record<string, string> = {
  shopify: "/platforms/shopify.png",
  amazon: "/platforms/amazon.png",
  tiktok: "/platforms/tiktok.png",
  walmart: "/platforms/walmart.png",
  ebay: "/platforms/ebay.png",
  etsy: "/platforms/etsy.png",
  shein: "/platforms/shein.png",
  temu: "/platforms/temu.png",
  chewy: "/platforms/chewy.png",
  wayfair: "/platforms/wayfair.png",
  whatnot: "/platforms/whatnot.png",
  bigcommerce: "/platforms/bigcommerce.png",
  woocommerce: "/platforms/woocommerce.png",
  magento: "/platforms/magento.png",
  bestbuy: "/platforms/bestbuy.png",
  costco: "/platforms/costco.png",
  homedepot: "/platforms/homedepot.png",
  newegg: "/platforms/newegg.png",
  squarespace: "/platforms/squarespace.png",
  targetplus: "/platforms/targetplus.png",
  wix: "/platforms/wix.png",
};
